.TH "fireqos\-params" "5" "Built 10 Jan 2016" "FireQOS Reference" "3.0.1"
.nh
.SH NAME
.PP
fireqos\-params \- shared class/match parameters
.SH SYNOPSIS
.PP
prio
.PP
priority
.SH DESCRIPTION
.PP
Some optional parameter names are the same for both \f[C]class\f[] and
\f[C]match\f[].
This page exists as a placeholder to help you find the appropriate
documentation.
.PP
If you are searching for FireQOS parameters in general, see both
fireqos\-params\-class(5) and/or
fireqos\-params\-match(5) depending upon your
need.
.TP
.B prio
For the \f[C]class\f[] version, see
fireqos\-params\-class(5).
.RS
.PP
For the \f[C]match\f[] version, see
fireqos\-params\-match(5).
.RE
.TP
.B priority
For the \f[C]class\f[] version, see
fireqos\-params\-match(5).
.RS
.PP
For the \f[C]match\f[] version, see
fireqos\-params\-class(5).
.RE
.SH SEE ALSO
.IP \[bu] 2
fireqos\-params\-class(5) \- QOS class
parameters
.IP \[bu] 2
fireqos\-params\-match(5) \- QOS match
parameters
.IP \[bu] 2
FireHOL Website (http://firehol.org/)
.IP \[bu] 2
FireQOS Online PDF Manual (http://firehol.org/fireqos-manual.pdf)
.IP \[bu] 2
FireQOS Online Documentation (http://firehol.org/documentation/)
.SH AUTHORS
FireHOL Team.
