.TH fireqos.conf 5 "Built 19 Oct 2014" "FireQOS Reference" "2.0.0-rc.3"
.nh
.SH NAME
.PP
fireqos.conf - FireQOS configuration file
.SH DESCRIPTION
.PP
This file defines the traffic shaping that will be applied by
fireqos(1).
.PP
The default configuration file is \f[C]/etc/firehol/fireqos.conf\f[].
It can be overridden from the command line.
.PP
A configuration consists of a number of input and output
\f[C]interface\f[] definitions (see
fireqos-interface(5)).
Each \f[C]interface\f[] can define any number of (optionally nested)
\f[C]class\f[]es (see fireqos-class(5)) which shape
the traffic which they \f[C]match\f[] (see
fireqos-match(5)).
.SH SPEED UNITS
.PP
In FireQOS, speeds can be expressed in the following units:
.TP
.B #\f[C]bps\f[]
# bytes per second
.RS
.RE
.TP
.B #\f[C]kbps\f[]; #\f[C]Kbps\f[]
# kilobytes per second
.RS
.RE
.TP
.B #\f[C]mbps\f[]; #\f[C]Mbps\f[]
# megabytes per second
.RS
.RE
.TP
.B #\f[C]gbps\f[]; #\f[C]Gbps\f[]
# gigabytes per second
.RS
.RE
.TP
.B #\f[C]bit\f[]
# bits per second
.RS
.RE
.TP
.B #\f[C]kbit\f[]; #\f[C]Kbit\f[]; #
# kilobits per second (default)
.RS
.RE
.TP
.B #\f[C]mbit\f[]; #\f[C]Mbit\f[]
# megabits per second
.RS
.RE
.TP
.B #\f[C]gbit\f[]; #\f[C]Gbit\f[]
# gigabits per second
.RS
.RE
.TP
.B #\f[C]%\f[]
In a \f[C]class\f[], uses this percentage of the enclosing
\f[C]rate\f[].
.RS
.RE
.RS
.PP
\f[B]Note\f[]
.PP
The default, \f[C]kbit\f[] is different to tc(8) which assumes bytes per
second when no unit is specified.
.RE
.SH EXAMPLE
.IP
.nf
\f[C]

\ #\ incoming\ traffic\ from\ my\ ADSL\ router
\ interface\ eth2\ adsl-in\ input\ rate\ 10500kbit\ adsl\ remote\ pppoe-llc
\ \ \ class\ voip\ commit\ 100kbit\ pfifo
\ \ \ \ \ match\ udp\ ports\ 5060,10000:10100\ #\ asterisk\ sip\ and\ rtp
\ \ \ \ \ match\ udp\ ports\ 16393:16402\ #\ apple\ facetime

\ \ \ class\ realtime\ commit\ 10%
\ \ \ \ \ match\ tcp\ port\ 22,1195:1198,1753\ #\ ssh,\ openvpn,\ pptp
\ \ \ \ \ match\ udp\ port\ 53\ #\ dns
\ \ \ \ \ match\ proto\ GRE
\ \ \ \ \ match\ icmp
\ \ \ \ \ match\ tcp\ syn
\ \ \ \ \ match\ tcp\ ack

\ \ \ class\ clients\ commit\ 10%
\ \ \ \ \ match\ tcp\ port\ 20,21,25,80,143,443,465,873,993\ #\ mail,\ web,\ ftp,\ etc

\ #\ unmatched\ traffic\ goes\ here\ (\[aq]default\[aq]\ is\ a\ special\ name)
\ \ \ class\ default\ max\ 90%

\ #\ I\ define\ torrents\ beneath\ the\ default\ class,\ so\ they\ slow
\ #\ down\ when\ the\ default\ class\ is\ willing\ to\ get\ bandwidth
\ \ \ class\ torrents\ max\ 90%
\ \ \ \ \ match\ port\ 51414\ #\ my\ torrent\ client

\ #\ outgoing\ traffic\ to\ my\ ADSL\ router
\ interface\ eth2\ adsl-out\ output\ rate\ 800kbit\ adsl\ remote\ pppoe-llc
\ \ \ class\ voip\ commit\ 100kbit\ pfifo
\ \ \ \ \ match\ udp\ ports\ 5060,10000:10100\ #\ asterisk\ sip\ and\ rtp
\ \ \ \ \ match\ udp\ ports\ 16393:16402\ #\ apple\ facetime

\ \ \ class\ realtime\ commit\ 10%
\ \ \ \ \ match\ tcp\ port\ 22,1195:1198,1753\ #\ ssh,\ openvpn,\ pptp
\ \ \ \ \ match\ udp\ port\ 53\ #\ dns
\ \ \ \ \ match\ proto\ GRE
\ \ \ \ \ match\ icmp
\ \ \ \ \ match\ tcp\ syn
\ \ \ \ \ match\ tcp\ ack

\ \ \ class\ clients\ commit\ 10%
\ \ \ \ \ match\ tcp\ port\ 20,21,25,80,143,443,465,873,993\ #\ mail,\ web,\ ftp,\ etc

\ #\ unmatched\ traffic\ goes\ here\ (\[aq]default\[aq]\ is\ a\ special\ name)
\ \ \ class\ default\ max\ 90%

\ #\ I\ define\ torrents\ beneath\ the\ default\ class,\ so\ they\ slow
\ #\ down\ when\ the\ default\ class\ is\ willing\ to\ get\ bandwidth
\ \ \ class\ torrents\ max\ 90%
\ \ \ \ \ match\ port\ 51414\ #\ my\ torrent\ client
\f[]
.fi
.SH SEE ALSO
.IP \[bu] 2
fireqos(1) - FireQOS program
.IP \[bu] 2
fireqos-interface(5) - QOS interface definition
.IP \[bu] 2
fireqos-class(5) - QOS class definition
.IP \[bu] 2
fireqos-match(5) - QOS traffic match
.IP \[bu] 2
FireHOL Website (http://firehol.org/)
.IP \[bu] 2
FireHOL Online PDF Manual (http://firehol.org/firehol-manual.pdf)
.IP \[bu] 2
FireHOL Online HTML Manual (http://firehol.org/manual)
.IP \[bu] 2
tc(8) (http://lartc.org/manpages/tc.html) - show / manipulate traffic
control settings
.SH AUTHORS
FireHOL Team.
