.TH "firehol\-group" "5" "Built 10 Jan 2016" "FireHOL Reference" "3.0.1"
.nh
.SH NAME
.PP
firehol\-group \- group commands with common options
.SH SYNOPSIS
.PP
group with \f[I]rule\-params\f[]
.PP
group end
.SH DESCRIPTION
.PP
The \f[C]group\f[] command allows you to group together multiple
\f[C]client\f[] and \f[C]server\f[] commands.
.PP
Grouping commands with common options (see
firehol\-params(5)) allows the option values to be
checked only once in the generated firewall rather than once per
service, making it more efficient.
.PP
Nested groups may be used.
.SH EXAMPLES
.PP
This:
.IP
.nf
\f[C]

interface\ any\ world
\ \ client\ all\ accept
\ \ server\ http\ accept

\ \ #\ Provide\ these\ services\ to\ trusted\ hosts\ only
\ \ server\ "ssh\ telnet"\ accept\ src\ "192.0.2.1\ 192.0.2.2"
\f[]
.fi
.PP
can be replaced to produce a more efficient firewall by this:
.IP
.nf
\f[C]

interface\ any\ world
\ \ client\ all\ accept
\ \ server\ http\ accept

\ \ #\ Provide\ these\ services\ to\ trusted\ hosts\ only
\ \ group\ with\ src\ "192.0.2.1\ 192.0.2.2"
\ \ \ \ server\ telnet\ accept
\ \ \ \ server\ ssh\ accept
\ \ group\ end
\f[]
.fi
.SH SEE ALSO
.IP \[bu] 2
firehol(1) \- FireHOL program
.IP \[bu] 2
firehol.conf(5) \- FireHOL configuration
.IP \[bu] 2
firehol\-interface(5) \- interface definition
.IP \[bu] 2
firehol\-router(5) \- router definition
.IP \[bu] 2
firehol\-params(5) \- optional rule parameters
.IP \[bu] 2
FireHOL Website (http://firehol.org/)
.IP \[bu] 2
FireHOL Online PDF Manual (http://firehol.org/firehol-manual.pdf)
.IP \[bu] 2
FireHOL Online Documentation (http://firehol.org/documentation/)
.SH AUTHORS
FireHOL Team.
