.TH firehol-action 5 "Built 19 Oct 2014" "FireHOL Reference" "2.0.0-rc.3"
.nh
.SH NAME
.PP
firehol-action - set up custom filter actions
.SH SYNOPSIS
.PP
action chain \f[I]name\f[] \f[I]action\f[]
.SH DESCRIPTION
.PP
The \f[C]action\f[] helper command creates an iptables(8) chain which
can be used to control the action of other firewall rules once the
firewall is running.
.PP
For example, you can setup the custom action ACT1, which by default is
ACCEPT, but can be dynamically changed to DROP, REJECT or RETURN (and
back) without restarting the firewall.
.PP
The \f[I]name\f[] can be any chain name accepted by iptables.
You should try to keep it within 5 and 10 characters.
.RS
.PP
\f[B]Note\f[]
.PP
The \f[I]name\f[]s created with this command are case-sensitive.
.RE
.PP
The \f[I]action\f[] can be any of those supported by FireHOL (see
firehol-actions(5)).
Only ACCEPT, REJECT, DROP, RETURN have any meaning in this instance.
.SH EXAMPLES
.PP
To create a custom chain and have some rules use it:
.IP
.nf
\f[C]
action\ chain\ ACT1\ accept

interface\ any\ world
\ \ \ \ server\ smtp\ ACT1
\ \ \ \ client\ smtp\ ACT1
\f[]
.fi
.PP
Once the firewall is running you can dynamically modify the behaviour of
the chain from the Linux command-line, as detailed below:
.PP
To insert a DROP action at the start of the chain to override the
default action (ACCEPT):
.IP
.nf
\f[C]
iptables\ -t\ filter\ -I\ ACT1\ -j\ DROP
\f[]
.fi
.PP
To delete the DROP action from the start of the chain to return to the
default action:
.IP
.nf
\f[C]
iptables\ -t\ filter\ -D\ ACT1\ -j\ DROP
\f[]
.fi
.RS
.PP
\f[B]Note\f[]
.PP
If you delete all of the rules in the chain, the default will be to
RETURN, in which case the behaviour will be as if any rules with the
action were not present in the configuration file.
.RE
.PP
You can also create multiple chains simultaneously.
To create 3 ACCEPT and 3 DROP chains you can do the following:
.IP
.nf
\f[C]
action\ chain\ "ACT1\ ACT2\ ACT3"\ accept
action\ chain\ "ACT4\ ACT5\ ACT6"\ drop
\f[]
.fi
.SH SEE ALSO
.IP \[bu] 2
firehol(1) - FireHOL program
.IP \[bu] 2
firehol.conf(5) - FireHOL configuration
.IP \[bu] 2
firehol-actions(5) - optional rule parameters
.IP \[bu] 2
iptables(8) (http://ipset.netfilter.org/iptables.man.html) -
administration tool for IPv4 firewalls
.IP \[bu] 2
ip6tables(8) (http://ipset.netfilter.org/ip6tables.man.html) -
administration tool for IPv6 firewalls
.IP \[bu] 2
FireHOL Website (http://firehol.org/)
.IP \[bu] 2
FireHOL Online PDF Manual (http://firehol.org/firehol-manual.pdf)
.IP \[bu] 2
FireHOL Online HTML Manual (http://firehol.org/manual)
.SH AUTHORS
FireHOL Team.
