.TH "firehol\-version" "5" "Built 10 Jan 2017" "FireHOL Reference" "3.1.1"
.nh
.SH NAME
.PP
firehol\-version \- set version number of configuration file
.SH SYNOPSIS
.PP
version 6
.SH DESCRIPTION
.PP
The \f[C]version\f[] helper command states the configuration file
version.
.PP
If the value passed is newer than the running version of FireHOL
supports, FireHOL will not run.
.PP
You do not have to specify a version number for a configuration file,
but by doing so you will prevent FireHOL trying to process a file which
it cannot handle.
.PP
The value that FireHOL expects is increased every time that the
configuration file format changes.
.RS
.PP
\f[B]Note\f[]
.PP
If you pass version 5 to FireHOL, it will disable IPv6 support and warn
you that you must update your configuration.
.RE
.SH SEE ALSO
.IP \[bu] 2
firehol(1) \- FireHOL program
.IP \[bu] 2
firehol.conf(5) \- FireHOL configuration
.IP \[bu] 2
FireHOL Website (http://firehol.org/)
.IP \[bu] 2
FireHOL Online PDF Manual (http://firehol.org/firehol-manual.pdf)
.IP \[bu] 2
FireHOL Online Documentation (http://firehol.org/documentation/)
.SH AUTHORS
FireHOL Team.
