.TH "firehol\-modifiers" "5" "Built 10 Jan 2016" "FireHOL Reference" "3.0.1"
.nh
.SH NAME
.PP
firehol\-modifiers \- select IPv4 or IPv6 mode
.SH SYNOPSIS
.PP
ipv4 \f[I]definition\-or\-command\f[] \f[I]argument\f[]...
.PP
ipv6 \f[I]definition\-or\-command\f[] \f[I]argument\f[]...
.SH DESCRIPTION
.PP
Without a modifier, interface and router definitions and commands that
come before either will be applied to both IPv4 and IPV6.
Commands within an \f[C]interface\f[] or \f[C]router\f[] assume the same
behaviour as the enclosing definition.
.PP
When preceded by a modifier, the command or definition can be made to
apply to IPv4 or IPv6 only.
Note that you cannot create an IPv4 only command within and IPv6
interface or vice\-versa.
.PP
Examples:
.IP
.nf
\f[C]

\ interface\ eth0\ myboth\ src4\ 192.0.2.0/24\ src6\ 2001:DB8::/24
\ \ \ ipv4\ server\ http\ accept
\ \ \ ipv6\ server\ http\ accept

\ ipv4\ interface\ eth0\ my4only\ src\ 192.0.2.0/24
\ \ \ server\ http\ accept

\ ipv6\ interface\ eth0\ my6only\ src\ 2001:DB8::/24
\ \ \ server\ http\ accept
\f[]
.fi
.PP
Many definitions and commands have explicitly named variants (such as
router4, router6, router46) which can be used as shorthand.
.SH SEE ALSO
.IP \[bu] 2
firehol(1) \- FireHOL program
.IP \[bu] 2
firehol.conf(5) \- FireHOL configuration
.IP \[bu] 2
firehol\-interface(5) \- interface definition
.IP \[bu] 2
firehol\-router(5) \- router definition
.IP \[bu] 2
firehol\-policy(5) \- policy command
.IP \[bu] 2
firehol\-protection(5) \- protection command
.IP \[bu] 2
firehol\-server(5) \- server, route commands
.IP \[bu] 2
firehol\-client(5) \- client command
.IP \[bu] 2
firehol\-group(5) \- group command
.IP \[bu] 2
firehol\-iptables(5) \- iptables helper
.IP \[bu] 2
firehol\-masquerade(5) \- masquerade helper
.IP \[bu] 2
FireHOL Website (http://firehol.org/)
.IP \[bu] 2
FireHOL Online PDF Manual (http://firehol.org/firehol-manual.pdf)
.IP \[bu] 2
FireHOL Online Documentation (http://firehol.org/documentation/)
.SH AUTHORS
FireHOL Team.
