.TH firehol-nat 5 "Built 06 Mar 2015" "FireHOL Reference" "2.0.2"
.nh
.SH NAME
.PP
firehol-nat - set up NAT and port redirections
.SH SYNOPSIS
.PP
{ nat to-destination | dnat [to] } \f[I]ipaddr\f[][:\f[I]port\f[]]
[\f[I]rule-params\f[]]
.PP
{ nat to-source | snat [to] } \f[I]ipaddr\f[][:\f[I]port\f[]]
[\f[I]rule-params\f[]]
.PP
{ nat redirect-to | redirect [to] } \f[I]port\f[][-\f[I]range\f[]]
[\f[I]rule-params\f[]]
.SH DESCRIPTION
.PP
Destination NAT is provided by \f[C]nat\ to-destination\f[] and its
synonym \f[C]dnat\f[].
.PP
Source NAT is provided by \f[C]nat\ to-source\f[] and its synonym
\f[C]snat\f[].
.PP
Redirection to a port on the local host is provided by
\f[C]nat\ redirect-to\f[] and its synonym \f[C]redirect\f[].
.PP
The \f[I]port\f[] part of the new address is optional with SNAT and
DNAT; if not specified it will not be changed.
.PP
When you apply NAT to a packet, the Linux kernel will track the changes
it makes, so that when it sees replies the transformation will be
applied in the opposite direction.
For instance if you changed the destination port of a packet from 80 to
8080, when a reply comes back, its source is set as 80.
This means the original sender is not aware a transformation is
happening.
.RS
.PP
\f[B]Note\f[]
.PP
The \f[I]rule-params\f[] are used only to determine the traffic that
will be matched for NAT in these commands, not to permit traffic to
flow.
.PP
Applying NAT does not automatically create rules to allow the traffic to
pass.
You will still need to include client or server entries in an interface
or router to allow the traffic.
.PP
When using \f[C]dnat\f[] or \f[C]redirect\f[], the transformation is in
the PREROUTING chain of the NAT table and happens before normal rules
are matched, so your client or server rule should match the "modified"
traffic.
.PP
When using \f[C]snat\f[], the transformation is in the POSTROUTING chain
of the NAT table and happens after normal rules are matched, so your
client or server rule should match the "unmodified" traffic.
.PP
See the netfilter flow
diagram (http://upload.wikimedia.org/wikipedia/commons/3/37/Netfilter-packet-flow.svg)
if you would like to see how network packets are processed by the kernel
in detail.
.RE
.PP
The \f[C]nat\f[] helper takes one of the following sub-commands:
.TP
.B to-destination \f[I]ipaddr\f[][:\f[I]port\f[]]
Defines a Destination NAT (DNAT).
Commonly thought of as port-forwarding (where packets destined for the
firewall with a given port and protocol are sent to a different IP
address and possibly port), DNAT is much more flexible in that any
number of parameters can be matched before the destination information
is rewritten.
.RS
.PP
\f[I]ipaddr\f[][:\f[I]port\f[]] is the destination address to be set in
packets matching \f[I]rule-params\f[].
.PP
If no rules are given, all forwarded traffic will be matched.
\f[C]outface\f[] should not be used in DNAT since the information is not
available at the time the decision is made.
.PP
\f[I]ipaddr\f[][:\f[I]port\f[]] accepts any \f[C]--to-destination\f[]
values that iptables(8) accepts.
Run \f[C]iptables\ -j\ DNAT\ --help\f[] for more information.
Multiple \f[I]ipaddr\f[][:\f[I]port\f[]] may be specified by separating
with spaces and enclosing with quotes.
.RE
.TP
.B to-source \f[I]ipaddr\f[][:\f[I]port\f[]]
Defines a Source NAT (SNAT).
SNAT is similar to masquerading but is more efficient for static IP
addresses.
You can use it to give a public IP address to a host which does not have
one behind the firewall.
See also firehol-masquerade(5).
.RS
.PP
\f[I]ipaddr\f[][:\f[I]port\f[]] is the source address to be set in
packets matching \f[I]rule-params\f[].
.PP
If no rules are given, all forwarded traffic will be matched.
\f[C]inface\f[] should not be used in SNAT since the information is not
available at the time the decision is made.
.PP
\f[I]ipaddr\f[][:\f[I]port\f[]] accepts any \f[C]--to-source\f[] values
that iptables(8) accepts.
Run \f[C]iptables\ -j\ SNAT\ --help\f[] for more information.
Multiple \f[I]ipaddr\f[][:\f[I]port\f[]] may be specified by separating
with spaces and enclosing with quotes.
.RE
.TP
.B redirect-to \f[I]port\f[][-\f[I]range\f[]]
Redirect matching traffic to the local machine.
This is typically useful if you want to intercept some traffic and
process it on the local machine.
.RS
.PP
\f[I]port\f[][-\f[I]range\f[]] is the port range (from-to) or single
port that packets matching \f[I]rule-params\f[] will be redirected to.
.PP
If no rules are given, all forwarded traffic will be matched.
\f[C]outface\f[] should not be used in REDIRECT since the information is
not available at the time the decision is made.
.RE
.SH EXAMPLES
.IP
.nf
\f[C]

\ #\ Port\ forwarding\ HTTP
\ dnat\ to\ 192.0.2.2\ proto\ tcp\ dport\ 80

\ #\ Port\ forwarding\ HTTPS\ on\ to\ a\ different\ port\ internally
\ dnat\ to\ 192.0.2.2:4443\ proto\ tcp\ dport\ 443

\ #\ Fix\ source\ for\ traffic\ leaving\ the\ firewall\ via\ eth0\ with\ private\ address
\ snat\ to\ 198.51.100.1\ outface\ eth0\ src\ 192.168.0.0/24

\ #\ Transparent\ squid\ (running\ on\ the\ firewall)\ for\ some\ hosts
\ redirect\ to\ 8080\ inface\ eth0\ src\ 198.51.100.0/24\ proto\ tcp\ dport\ 80

\ #\ Send\ to\ 192.0.2.1
\ #\ \ -\ all\ traffic\ arriving\ at\ or\ passing\ through\ the\ firewall
\ nat\ to-destination\ 192.0.2.1

\ #\ Send\ to\ 192.0.2.1
\ #\ \ -\ all\ traffic\ arriving\ at\ or\ passing\ through\ the\ firewall
\ #\ \ -\ which\ WAS\ going\ to\ 203.0.113.1
\ nat\ to-destination\ 192.0.2.1\ dst\ 203.0.113.1

\ #\ Send\ to\ 192.0.2.1
\ #\ \ -\ TCP\ traffic\ arriving\ at\ or\ passing\ through\ the\ firewall
\ #\ \ -\ which\ WAS\ going\ to\ 203.0.113.1
\ nat\ to-destination\ 192.0.2.1\ proto\ tcp\ dst\ 203.0.113.1

\ #\ Send\ to\ 192.0.2.1
\ #\ \ -\ TCP\ traffic\ arriving\ at\ or\ passing\ through\ the\ firewall
\ #\ \ -\ which\ WAS\ going\ to\ 203.0.113.1,\ port\ 25
\ nat\ to-destination\ 192.0.2.1\ proto\ tcp\ dport\ 25\ dst\ 203.0.113.1
\f[]
.fi
.SH SEE ALSO
.IP \[bu] 2
firehol(1) - FireHOL program
.IP \[bu] 2
firehol.conf(5) - FireHOL configuration
.IP \[bu] 2
firehol-interface(5) - interface definition
.IP \[bu] 2
firehol-router(5) - router definition
.IP \[bu] 2
firehol-params(5) - optional rule parameters
.IP \[bu] 2
firehol-masquerade(5) - masquerade helper
.IP \[bu] 2
FireHOL Website (http://firehol.org/)
.IP \[bu] 2
FireHOL Online PDF Manual (http://firehol.org/firehol-manual.pdf)
.IP \[bu] 2
FireHOL Online HTML Manual (http://firehol.org/manual)
.IP \[bu] 2
NAT
HOWTO (http://www.netfilter.org/documentation/HOWTO/NAT-HOWTO-6.html)
.IP \[bu] 2
netfilter flow
diagram (http://upload.wikimedia.org/wikipedia/commons/3/37/Netfilter-packet-flow.svg)
.SH AUTHORS
FireHOL Team.
