.TH "firehol\-iptables" "5" "Built 10 Jan 2016" "FireHOL Reference" "3.0.1"
.nh
.SH NAME
.PP
firehol\-iptables \- include custom iptables commands
.SH SYNOPSIS
.PP
iptables \f[I]argument\f[]...
.PP
ip6tables \f[I]argument\f[]...
.SH DESCRIPTION
.PP
The \f[C]iptables\f[] and \f[C]ip6tables\f[] helper commands pass all of
their \f[I]argument\f[]s to the real iptables(8) or ip6tables(8) at the
appropriate point during run\-time.
.RS
.PP
\f[B]Note\f[]
.PP
When used in an \f[C]interface\f[] or \f[C]router\f[], the result will
not have a direct relationship to the enclosing definition as the
parameters passed are only those you supply.
.RE
.PP
You should not use \f[C]/sbin/iptables\f[] or \f[C]/sbin/ip6tables\f[]
directly in a FireHOL configuration as they will run before FireHOL
activates its firewall.
This means that the commands are applied to the previously running
firewall, not the new firewall, and will be lost when the new firewall
is activated.
.PP
The \f[C]iptables\f[] and \f[C]ip6tables\f[] helpers are provided to
allow you to hook in commands safely.
.SH SEE ALSO
.IP \[bu] 2
firehol(1) \- FireHOL program
.IP \[bu] 2
firehol.conf(5) \- FireHOL configuration
.IP \[bu] 2
iptables(8) (http://ipset.netfilter.org/iptables.man.html) \-
administration tool for IPv4 firewalls
.IP \[bu] 2
ip6tables(8) (http://ipset.netfilter.org/ip6tables.man.html) \-
administration tool for IPv6 firewalls
.IP \[bu] 2
FireHOL Website (http://firehol.org/)
.IP \[bu] 2
FireHOL Online PDF Manual (http://firehol.org/firehol-manual.pdf)
.IP \[bu] 2
FireHOL Online Documentation (http://firehol.org/documentation/)
.SH AUTHORS
FireHOL Team.
