.TH "firehol\-mark" "5" "Built 10 Jan 2017" "FireHOL Reference" "3.1.1"
.nh
.SH NAME
.PP
firehol\-mark \- mark traffic for traffic shaping tools
.SH SYNOPSIS
.PP
\f[I]Warning \- this manual page is out of date for nightly build/v3
behaviour\f[]
.PP
mark \f[I]value\f[] \f[I]chain\f[] \f[I]rule\-params\f[]
.SH DESCRIPTION
.PP
The \f[C]mark\f[] helper command sets a mark on packets that can be
matched by traffic shaping tools for controlling the traffic.
.RS
.PP
\f[B]Note\f[]
.PP
To set a mark on whole connections, see
firehol\-connmark(5).
There is also a \f[C]mark\f[] parameter which allows matching marks
within individual rules (see firehol\-params(5)).
.RE
.PP
The \f[I]value\f[] is the mark value to set (a 32 bit integer).
.PP
The \f[I]chain\f[] will be used to find traffic to mark.
It can be any of the iptables(8) built in chains belonging to the
\f[C]mangle\f[] table.
The chain names are: INPUT, FORWARD, OUTPUT, PREROUTING and POSTROUTING.
The names are case\-sensitive.
.PP
The \f[I]rule\-params\f[] define a set of rule parameters to match the
traffic that is to be marked within the chosen chain.
See firehol\-params(5) for more details.
.PP
Any \f[C]mark\f[] commands will affect all traffic matched.
They must be declared before the first router or interface.
.RS
.PP
\f[B]Note\f[]
.PP
If you want to do policy based routing based on iptables(8) marks, you
will need to disable the Root Path Filtering on the interfaces involved
(rp_filter in sysctl).
.RE
.SH EXAMPLES
.IP
.nf
\f[C]
\ #\ mark\ with\ 1,\ packets\ sent\ by\ the\ local\ machine
\ mark\ 1\ OUTPUT

\ #\ mark\ with\ 2,\ packets\ routed\ by\ the\ local\ machine
\ mark\ 2\ FORWARD

\ #\ mark\ with\ 3,\ packets\ routed\ by\ the\ local\ machine,\ sent\ from
\ #\ \ \ \ \ \ \ \ \ \ \ \ \ \ 192.0.2.2\ destined\ for\ port\ TCP/25\ of\ 198.51.100.1
\ mark\ 3\ FORWARD\ proto\ tcp\ dport\ 25\ dst\ 198.51.100.1\ src\ 192.0.2.2
\f[]
.fi
.SH SEE ALSO
.IP \[bu] 2
firehol(1) \- FireHOL program
.IP \[bu] 2
firehol.conf(5) \- FireHOL configuration
.IP \[bu] 2
firehol\-params(5) \- optional rule parameters
.IP \[bu] 2
firehol\-connmark(5) \- set a stateful mark on a
connection
.IP \[bu] 2
iptables(8) (http://ipset.netfilter.org/iptables.man.html) \-
administration tool for IPv4 firewalls
.IP \[bu] 2
ip6tables(8) (http://ipset.netfilter.org/ip6tables.man.html) \-
administration tool for IPv6 firewalls
.IP \[bu] 2
ip(8) \- show / manipulate routing, devices, policy routing and tunnels
.IP \[bu] 2
FireHOL Website (http://firehol.org/)
.IP \[bu] 2
FireHOL Online PDF Manual (http://firehol.org/firehol-manual.pdf)
.IP \[bu] 2
FireHOL Online Documentation (http://firehol.org/documentation/)
.IP \[bu] 2
Linux Advanced Routing & Traffic Control HOWTO (http://lartc.org/howto/)
.SH AUTHORS
FireHOL Team.
